development:
  adapter: postgresql
  encoding: unicode
  database: database_name_development
  pool: 5
  host: localhost
  username: "ilia"
  password: "123456"

test:
  adapter: postgresql
  encoding: unicode
  database: database_name_test
  pool: 5
  username: "ilia"
  password: "123456"

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 
